version: '3.8'

services:
  text-pipeline:
    build: .
    container_name: ai-text-processing
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENV=${PINECONE_ENV}
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
